
resource.dir:     resource.dir
grammar.dir:      grammars/cplanner/

config.quiz:      share/quiz.properties
mapper.project:    grammars/cplanner/mapper/allrules-integrated

dut: {
    generation.project.dut:     grammars/cplanner/dutch/allrules
    analysis.project:     analysis.project
}
eng: {
    generation.project.eng:     grammars/cplanner/english/allrules
    analysis.project:     analysis.project
}
ita: {
    generation.project.ita:     grammars/cplanner/italianLF/allrules_lf
    analysis.project:     analysis.project
}
de: {
    generation.project.de:     grammars/cplanner/german/allrules
    analysis.project:     analysis.project
}

