outputDirectory:    src/main/gen-java
wrapperClass:       de.dfki.dialogue.NaoAgent
serverHost:         localhost
serverPort:         9090
ontologyFile:       src/main/resources/ontologies/pal.ini
checkTypes:         true
failOnError:        false
targetConstructor:  
rootPackage:        de.dfki.dialogue
nameToURI:
  Activity : "<dom:Activity>"
  Child : "<dom:Child>"
