outputDirectory:    src/main/gen-java
wrapperClass:       de.dfki.dialogue.Foo
serverHost:         localhost
serverPort:         9090
ontologyFile:       src/test/resources/ontos/pal.ini
checkTypes:         true
failOnError:        false
targetConstructor:
rootPackage:        de.dfki.dialogue
nameToURI:
  Activity : "<dom:Activity>"
  Child : "<dom:Child>"
